// Code generated by protoc-gen-gorums. DO NOT EDIT.
// versions:
// 	protoc-gen-gorums v0.11.0-devel
// 	protoc            v7.34.1
// source: proto/diemrpc/diem.proto

package diemrpc

import (
	diempb "github.com/DanyGoT/HotStuffs/proto/diempb"
	gorums "github.com/relab/gorums"
	gorumsimpl "github.com/relab/gorums/runtime/gorumsimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = gorumsimpl.EnforceVersion(11 - gorumsimpl.MinVersion)
	// Verify that the gorums runtime is sufficiently up-to-date.
	_ = gorumsimpl.EnforceVersion(gorumsimpl.MaxVersion - 11)
)

// The type aliases below are useful Gorums types that we make accessible
// from generated code. These names therefore become reserved identifiers,
// meaning that proto message types with these names would collide with the
// generated aliases and cause a compile error.
//
// The bundler (gorums_bundle.go) is responsible for discovering these
// aliases and any other identifiers defined herein, and adding them to
// the reserved identifiers list.
//
// If necessary, additional aliases and other identifiers should be added in
// the generator's cmd/protoc-gen-gorums/dev directory, and the bundler will
// automatically discover them and add them to the reserved identifiers list.

type (
	Config        = gorums.Config
	Node          = gorums.Node
	NodeContext   = gorums.NodeContext
	ConfigContext = gorums.ConfigContext
)

// Reference imports to suppress errors if they are not otherwise used.
var _ emptypb.Empty

// Proposal is a multicast call invoked on all nodes in the configuration in ctx.
// It returns a one-way call handle; call Send to block until every send
// completes and observe any send errors, or Async to dispatch without waiting.
// Use gorums.MapRequest to send different messages to each node.
//
// Example:
//
//	err := Proposal(ctx, in).Send()
//	h := Proposal(ctx, in).Async(); err := h.Wait()
func Proposal(ctx *ConfigContext, in *diempb.ProposalMsg) *gorums.OnewayCall[*diempb.ProposalMsg] {
	return gorumsimpl.Multicast(ctx, in, "diemrpc.Diem.Proposal")
}

// Unicast: DiemBFT 3.1 sends a vote to the leader of the next round alone,
// because that leader is the only replica that will propose over the
// certificate.
//
// Example:
//
//	err := Vote(ctx, in).Send()
//	h := Vote(ctx, in).Async(); err := h.Wait()
func Vote(ctx *NodeContext, in *diempb.VoteMsg) *gorums.OnewayCall[*diempb.VoteMsg] {
	return gorumsimpl.Unicast(ctx, in, "diemrpc.Diem.Vote")
}

// Timeout is a multicast call invoked on all nodes in the configuration in ctx.
// It returns a one-way call handle; call Send to block until every send
// completes and observe any send errors, or Async to dispatch without waiting.
// Use gorums.MapRequest to send different messages to each node.
//
// Example:
//
//	err := Timeout(ctx, in).Send()
//	h := Timeout(ctx, in).Async(); err := h.Wait()
func Timeout(ctx *ConfigContext, in *diempb.TimeoutMsg) *gorums.OnewayCall[*diempb.TimeoutMsg] {
	return gorumsimpl.Multicast(ctx, in, "diemrpc.Diem.Timeout")
}

// Diem is the server-side API for the Diem Service
type DiemServer interface {
	Proposal(gorums.ServerContext, *diempb.ProposalMsg)
	Vote(gorums.ServerContext, *diempb.VoteMsg)
	Timeout(gorums.ServerContext, *diempb.TimeoutMsg)
}

func RegisterDiemServer(srv *gorums.Server, impl DiemServer) {
	srv.RegisterHandler("diemrpc.Diem.Proposal", func(ctx gorums.ServerContext, in *gorums.Message) (*gorums.Message, error) {
		req := gorums.AsProto[*diempb.ProposalMsg](in)
		impl.Proposal(ctx, req)
		return nil, nil
	})
	srv.RegisterHandler("diemrpc.Diem.Vote", func(ctx gorums.ServerContext, in *gorums.Message) (*gorums.Message, error) {
		req := gorums.AsProto[*diempb.VoteMsg](in)
		impl.Vote(ctx, req)
		return nil, nil
	})
	srv.RegisterHandler("diemrpc.Diem.Timeout", func(ctx gorums.ServerContext, in *gorums.Message) (*gorums.Message, error) {
		req := gorums.AsProto[*diempb.TimeoutMsg](in)
		impl.Timeout(ctx, req)
		return nil, nil
	})
}
