// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.34.1
// source: proto/diemrpc/diem.proto

package diemrpc

import (
	diempb "github.com/DanyGoT/HotStuffs/proto/diempb"
	_ "github.com/relab/gorums"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_proto_diemrpc_diem_proto protoreflect.FileDescriptor

const file_proto_diemrpc_diem_proto_rawDesc = "" +
	"\n" +
	"\x18proto/diemrpc/diem.proto\x12\adiemrpc\x1a\fgorums.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x17proto/diempb/diem.proto2\xb9\x01\n" +
	"\x04Diem\x12=\n" +
	"\bProposal\x12\x13.diempb.ProposalMsg\x1a\x16.google.protobuf.Empty\"\x04\x98\xb5\x18\x01\x125\n" +
	"\x04Vote\x12\x0f.diempb.VoteMsg\x1a\x16.google.protobuf.Empty\"\x04\x90\xb5\x18\x01\x12;\n" +
	"\aTimeout\x12\x12.diempb.TimeoutMsg\x1a\x16.google.protobuf.Empty\"\x04\x98\xb5\x18\x01B/Z*github.com/DanyGoT/HotStuffs/proto/diemrpc\x92\x03\x00b\beditionsp\xe9\a"

var file_proto_diemrpc_diem_proto_goTypes = []any{
	(*diempb.ProposalMsg)(nil), // 0: diempb.ProposalMsg
	(*diempb.VoteMsg)(nil),     // 1: diempb.VoteMsg
	(*diempb.TimeoutMsg)(nil),  // 2: diempb.TimeoutMsg
	(*emptypb.Empty)(nil),      // 3: google.protobuf.Empty
}
var file_proto_diemrpc_diem_proto_depIdxs = []int32{
	0, // 0: diemrpc.Diem.Proposal:input_type -> diempb.ProposalMsg
	1, // 1: diemrpc.Diem.Vote:input_type -> diempb.VoteMsg
	2, // 2: diemrpc.Diem.Timeout:input_type -> diempb.TimeoutMsg
	3, // 3: diemrpc.Diem.Proposal:output_type -> google.protobuf.Empty
	3, // 4: diemrpc.Diem.Vote:output_type -> google.protobuf.Empty
	3, // 5: diemrpc.Diem.Timeout:output_type -> google.protobuf.Empty
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_diemrpc_diem_proto_init() }
func file_proto_diemrpc_diem_proto_init() {
	if File_proto_diemrpc_diem_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_diemrpc_diem_proto_rawDesc), len(file_proto_diemrpc_diem_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_diemrpc_diem_proto_goTypes,
		DependencyIndexes: file_proto_diemrpc_diem_proto_depIdxs,
	}.Build()
	File_proto_diemrpc_diem_proto = out.File
	file_proto_diemrpc_diem_proto_goTypes = nil
	file_proto_diemrpc_diem_proto_depIdxs = nil
}
