// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.34.1
// source: proto/diempb/diem.proto

package diempb

import (
	_ "github.com/relab/gorums"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// signer is a *claim*: meaningful only once sig verifies against the public key
// registered for that ID. Gorums exposes no authenticated sender identity, so
// authentication is by signature, never by connection.
type Signature struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Signer uint32                 `protobuf:"varint,1,opt,name=signer"`
	xxx_hidden_Sig    []byte                 `protobuf:"bytes,2,opt,name=sig"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Signature) Reset() {
	*x = Signature{}
	mi := &file_proto_diempb_diem_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Signature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Signature) ProtoMessage() {}

func (x *Signature) ProtoReflect() protoreflect.Message {
	mi := &file_proto_diempb_diem_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Signature) GetSigner() uint32 {
	if x != nil {
		return x.xxx_hidden_Signer
	}
	return 0
}

func (x *Signature) GetSig() []byte {
	if x != nil {
		return x.xxx_hidden_Sig
	}
	return nil
}

func (x *Signature) SetSigner(v uint32) {
	x.xxx_hidden_Signer = v
}

func (x *Signature) SetSig(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Sig = v
}

type Signature_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Signer uint32
	Sig    []byte
}

func (b0 Signature_builder) Build() *Signature {
	m0 := &Signature{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Signer = b.Signer
	x.xxx_hidden_Sig = b.Sig
	return m0
}

// The parent's id and round travel with the vote so a receiver can decide
// commitment from one block without walking its ancestry.
type VoteInfo struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id          []byte                 `protobuf:"bytes,1,opt,name=id"`
	xxx_hidden_Round       uint64                 `protobuf:"varint,2,opt,name=round"`
	xxx_hidden_ParentId    []byte                 `protobuf:"bytes,3,opt,name=parent_id,json=parentId"`
	xxx_hidden_ParentRound uint64                 `protobuf:"varint,4,opt,name=parent_round,json=parentRound"`
	xxx_hidden_ExecStateId []byte                 `protobuf:"bytes,5,opt,name=exec_state_id,json=execStateId"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *VoteInfo) Reset() {
	*x = VoteInfo{}
	mi := &file_proto_diempb_diem_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VoteInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoteInfo) ProtoMessage() {}

func (x *VoteInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_diempb_diem_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *VoteInfo) GetId() []byte {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return nil
}

func (x *VoteInfo) GetRound() uint64 {
	if x != nil {
		return x.xxx_hidden_Round
	}
	return 0
}

func (x *VoteInfo) GetParentId() []byte {
	if x != nil {
		return x.xxx_hidden_ParentId
	}
	return nil
}

func (x *VoteInfo) GetParentRound() uint64 {
	if x != nil {
		return x.xxx_hidden_ParentRound
	}
	return 0
}

func (x *VoteInfo) GetExecStateId() []byte {
	if x != nil {
		return x.xxx_hidden_ExecStateId
	}
	return nil
}

func (x *VoteInfo) SetId(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Id = v
}

func (x *VoteInfo) SetRound(v uint64) {
	x.xxx_hidden_Round = v
}

func (x *VoteInfo) SetParentId(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_ParentId = v
}

func (x *VoteInfo) SetParentRound(v uint64) {
	x.xxx_hidden_ParentRound = v
}

func (x *VoteInfo) SetExecStateId(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_ExecStateId = v
}

type VoteInfo_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id          []byte
	Round       uint64
	ParentId    []byte
	ParentRound uint64
	ExecStateId []byte
}

func (b0 VoteInfo_builder) Build() *VoteInfo {
	m0 := &VoteInfo{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Id = b.Id
	x.xxx_hidden_Round = b.Round
	x.xxx_hidden_ParentId = b.ParentId
	x.xxx_hidden_ParentRound = b.ParentRound
	x.xxx_hidden_ExecStateId = b.ExecStateId
	return m0
}

type LedgerCommitInfo struct {
	state                    protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_CommitStateId []byte                 `protobuf:"bytes,1,opt,name=commit_state_id,json=commitStateId"`
	xxx_hidden_VoteInfoHash  []byte                 `protobuf:"bytes,2,opt,name=vote_info_hash,json=voteInfoHash"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *LedgerCommitInfo) Reset() {
	*x = LedgerCommitInfo{}
	mi := &file_proto_diempb_diem_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LedgerCommitInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LedgerCommitInfo) ProtoMessage() {}

func (x *LedgerCommitInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_diempb_diem_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *LedgerCommitInfo) GetCommitStateId() []byte {
	if x != nil {
		return x.xxx_hidden_CommitStateId
	}
	return nil
}

func (x *LedgerCommitInfo) GetVoteInfoHash() []byte {
	if x != nil {
		return x.xxx_hidden_VoteInfoHash
	}
	return nil
}

func (x *LedgerCommitInfo) SetCommitStateId(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_CommitStateId = v
}

func (x *LedgerCommitInfo) SetVoteInfoHash(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_VoteInfoHash = v
}

type LedgerCommitInfo_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	CommitStateId []byte
	VoteInfoHash  []byte
}

func (b0 LedgerCommitInfo_builder) Build() *LedgerCommitInfo {
	m0 := &LedgerCommitInfo{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_CommitStateId = b.CommitStateId
	x.xxx_hidden_VoteInfoHash = b.VoteInfoHash
	return m0
}

// signatures is ordered by signer and must stay that way: a block id covers the
// slice byte for byte, so a permuted certificate is a different block.
// author_sig is absent only on the genesis certificate, which is trusted rather
// than certified.
type QuorumCert struct {
	state                       protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_VoteInfo         *VoteInfo              `protobuf:"bytes,1,opt,name=vote_info,json=voteInfo"`
	xxx_hidden_LedgerCommitInfo *LedgerCommitInfo      `protobuf:"bytes,2,opt,name=ledger_commit_info,json=ledgerCommitInfo"`
	xxx_hidden_Signatures       *[]*Signature          `protobuf:"bytes,3,rep,name=signatures"`
	xxx_hidden_Author           uint32                 `protobuf:"varint,4,opt,name=author"`
	xxx_hidden_AuthorSig        *Signature             `protobuf:"bytes,5,opt,name=author_sig,json=authorSig"`
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *QuorumCert) Reset() {
	*x = QuorumCert{}
	mi := &file_proto_diempb_diem_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuorumCert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuorumCert) ProtoMessage() {}

func (x *QuorumCert) ProtoReflect() protoreflect.Message {
	mi := &file_proto_diempb_diem_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *QuorumCert) GetVoteInfo() *VoteInfo {
	if x != nil {
		return x.xxx_hidden_VoteInfo
	}
	return nil
}

func (x *QuorumCert) GetLedgerCommitInfo() *LedgerCommitInfo {
	if x != nil {
		return x.xxx_hidden_LedgerCommitInfo
	}
	return nil
}

func (x *QuorumCert) GetSignatures() []*Signature {
	if x != nil {
		if x.xxx_hidden_Signatures != nil {
			return *x.xxx_hidden_Signatures
		}
	}
	return nil
}

func (x *QuorumCert) GetAuthor() uint32 {
	if x != nil {
		return x.xxx_hidden_Author
	}
	return 0
}

func (x *QuorumCert) GetAuthorSig() *Signature {
	if x != nil {
		return x.xxx_hidden_AuthorSig
	}
	return nil
}

func (x *QuorumCert) SetVoteInfo(v *VoteInfo) {
	x.xxx_hidden_VoteInfo = v
}

func (x *QuorumCert) SetLedgerCommitInfo(v *LedgerCommitInfo) {
	x.xxx_hidden_LedgerCommitInfo = v
}

func (x *QuorumCert) SetSignatures(v []*Signature) {
	x.xxx_hidden_Signatures = &v
}

func (x *QuorumCert) SetAuthor(v uint32) {
	x.xxx_hidden_Author = v
}

func (x *QuorumCert) SetAuthorSig(v *Signature) {
	x.xxx_hidden_AuthorSig = v
}

func (x *QuorumCert) HasVoteInfo() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_VoteInfo != nil
}

func (x *QuorumCert) HasLedgerCommitInfo() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_LedgerCommitInfo != nil
}

func (x *QuorumCert) HasAuthorSig() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_AuthorSig != nil
}

func (x *QuorumCert) ClearVoteInfo() {
	x.xxx_hidden_VoteInfo = nil
}

func (x *QuorumCert) ClearLedgerCommitInfo() {
	x.xxx_hidden_LedgerCommitInfo = nil
}

func (x *QuorumCert) ClearAuthorSig() {
	x.xxx_hidden_AuthorSig = nil
}

type QuorumCert_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	VoteInfo         *VoteInfo
	LedgerCommitInfo *LedgerCommitInfo
	Signatures       []*Signature
	Author           uint32
	AuthorSig        *Signature
}

func (b0 QuorumCert_builder) Build() *QuorumCert {
	m0 := &QuorumCert{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_VoteInfo = b.VoteInfo
	x.xxx_hidden_LedgerCommitInfo = b.LedgerCommitInfo
	x.xxx_hidden_Signatures = &b.Signatures
	x.xxx_hidden_Author = b.Author
	x.xxx_hidden_AuthorSig = b.AuthorSig
	return m0
}

// One slice of pairs, not the paper's two parallel vectors: each signature
// covers (tc.round, its own high_qc_round), so a misalignment would verify a
// signer against somebody else's reported round.
type TimeoutVote struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_HighQcRound uint64                 `protobuf:"varint,1,opt,name=high_qc_round,json=highQcRound"`
	xxx_hidden_Sig         *Signature             `protobuf:"bytes,2,opt,name=sig"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *TimeoutVote) Reset() {
	*x = TimeoutVote{}
	mi := &file_proto_diempb_diem_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeoutVote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeoutVote) ProtoMessage() {}

func (x *TimeoutVote) ProtoReflect() protoreflect.Message {
	mi := &file_proto_diempb_diem_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *TimeoutVote) GetHighQcRound() uint64 {
	if x != nil {
		return x.xxx_hidden_HighQcRound
	}
	return 0
}

func (x *TimeoutVote) GetSig() *Signature {
	if x != nil {
		return x.xxx_hidden_Sig
	}
	return nil
}

func (x *TimeoutVote) SetHighQcRound(v uint64) {
	x.xxx_hidden_HighQcRound = v
}

func (x *TimeoutVote) SetSig(v *Signature) {
	x.xxx_hidden_Sig = v
}

func (x *TimeoutVote) HasSig() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Sig != nil
}

func (x *TimeoutVote) ClearSig() {
	x.xxx_hidden_Sig = nil
}

type TimeoutVote_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	HighQcRound uint64
	Sig         *Signature
}

func (b0 TimeoutVote_builder) Build() *TimeoutVote {
	m0 := &TimeoutVote{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_HighQcRound = b.HighQcRound
	x.xxx_hidden_Sig = b.Sig
	return m0
}

type TimeoutCert struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Round uint64                 `protobuf:"varint,1,opt,name=round"`
	xxx_hidden_Votes *[]*TimeoutVote        `protobuf:"bytes,2,rep,name=votes"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TimeoutCert) Reset() {
	*x = TimeoutCert{}
	mi := &file_proto_diempb_diem_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeoutCert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeoutCert) ProtoMessage() {}

func (x *TimeoutCert) ProtoReflect() protoreflect.Message {
	mi := &file_proto_diempb_diem_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *TimeoutCert) GetRound() uint64 {
	if x != nil {
		return x.xxx_hidden_Round
	}
	return 0
}

func (x *TimeoutCert) GetVotes() []*TimeoutVote {
	if x != nil {
		if x.xxx_hidden_Votes != nil {
			return *x.xxx_hidden_Votes
		}
	}
	return nil
}

func (x *TimeoutCert) SetRound(v uint64) {
	x.xxx_hidden_Round = v
}

func (x *TimeoutCert) SetVotes(v []*TimeoutVote) {
	x.xxx_hidden_Votes = &v
}

type TimeoutCert_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Round uint64
	Votes []*TimeoutVote
}

func (b0 TimeoutCert_builder) Build() *TimeoutCert {
	m0 := &TimeoutCert{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Round = b.Round
	x.xxx_hidden_Votes = &b.Votes
	return m0
}

// No id field: the receiver recomputes it from the fields, so no digest is ever
// taken from the wire.
type Block struct {
	state              protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Author  uint32                 `protobuf:"varint,1,opt,name=author"`
	xxx_hidden_Round   uint64                 `protobuf:"varint,2,opt,name=round"`
	xxx_hidden_Payload [][]byte               `protobuf:"bytes,3,rep,name=payload"`
	xxx_hidden_Qc      *QuorumCert            `protobuf:"bytes,4,opt,name=qc"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Block) Reset() {
	*x = Block{}
	mi := &file_proto_diempb_diem_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Block) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Block) ProtoMessage() {}

func (x *Block) ProtoReflect() protoreflect.Message {
	mi := &file_proto_diempb_diem_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Block) GetAuthor() uint32 {
	if x != nil {
		return x.xxx_hidden_Author
	}
	return 0
}

func (x *Block) GetRound() uint64 {
	if x != nil {
		return x.xxx_hidden_Round
	}
	return 0
}

func (x *Block) GetPayload() [][]byte {
	if x != nil {
		return x.xxx_hidden_Payload
	}
	return nil
}

func (x *Block) GetQc() *QuorumCert {
	if x != nil {
		return x.xxx_hidden_Qc
	}
	return nil
}

func (x *Block) SetAuthor(v uint32) {
	x.xxx_hidden_Author = v
}

func (x *Block) SetRound(v uint64) {
	x.xxx_hidden_Round = v
}

func (x *Block) SetPayload(v [][]byte) {
	x.xxx_hidden_Payload = v
}

func (x *Block) SetQc(v *QuorumCert) {
	x.xxx_hidden_Qc = v
}

func (x *Block) HasQc() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Qc != nil
}

func (x *Block) ClearQc() {
	x.xxx_hidden_Qc = nil
}

type Block_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Author  uint32
	Round   uint64
	Payload [][]byte
	Qc      *QuorumCert
}

func (b0 Block_builder) Build() *Block {
	m0 := &Block{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Author = b.Author
	x.xxx_hidden_Round = b.Round
	x.xxx_hidden_Payload = b.Payload
	x.xxx_hidden_Qc = b.Qc
	return m0
}

type ProposalMsg struct {
	state                   protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Block        *Block                 `protobuf:"bytes,1,opt,name=block"`
	xxx_hidden_LastRoundTc  *TimeoutCert           `protobuf:"bytes,2,opt,name=last_round_tc,json=lastRoundTc"`
	xxx_hidden_HighCommitQc *QuorumCert            `protobuf:"bytes,3,opt,name=high_commit_qc,json=highCommitQc"`
	xxx_hidden_Sender       uint32                 `protobuf:"varint,4,opt,name=sender"`
	xxx_hidden_Sig          *Signature             `protobuf:"bytes,5,opt,name=sig"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *ProposalMsg) Reset() {
	*x = ProposalMsg{}
	mi := &file_proto_diempb_diem_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProposalMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProposalMsg) ProtoMessage() {}

func (x *ProposalMsg) ProtoReflect() protoreflect.Message {
	mi := &file_proto_diempb_diem_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ProposalMsg) GetBlock() *Block {
	if x != nil {
		return x.xxx_hidden_Block
	}
	return nil
}

func (x *ProposalMsg) GetLastRoundTc() *TimeoutCert {
	if x != nil {
		return x.xxx_hidden_LastRoundTc
	}
	return nil
}

func (x *ProposalMsg) GetHighCommitQc() *QuorumCert {
	if x != nil {
		return x.xxx_hidden_HighCommitQc
	}
	return nil
}

func (x *ProposalMsg) GetSender() uint32 {
	if x != nil {
		return x.xxx_hidden_Sender
	}
	return 0
}

func (x *ProposalMsg) GetSig() *Signature {
	if x != nil {
		return x.xxx_hidden_Sig
	}
	return nil
}

func (x *ProposalMsg) SetBlock(v *Block) {
	x.xxx_hidden_Block = v
}

func (x *ProposalMsg) SetLastRoundTc(v *TimeoutCert) {
	x.xxx_hidden_LastRoundTc = v
}

func (x *ProposalMsg) SetHighCommitQc(v *QuorumCert) {
	x.xxx_hidden_HighCommitQc = v
}

func (x *ProposalMsg) SetSender(v uint32) {
	x.xxx_hidden_Sender = v
}

func (x *ProposalMsg) SetSig(v *Signature) {
	x.xxx_hidden_Sig = v
}

func (x *ProposalMsg) HasBlock() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Block != nil
}

func (x *ProposalMsg) HasLastRoundTc() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_LastRoundTc != nil
}

func (x *ProposalMsg) HasHighCommitQc() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_HighCommitQc != nil
}

func (x *ProposalMsg) HasSig() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Sig != nil
}

func (x *ProposalMsg) ClearBlock() {
	x.xxx_hidden_Block = nil
}

func (x *ProposalMsg) ClearLastRoundTc() {
	x.xxx_hidden_LastRoundTc = nil
}

func (x *ProposalMsg) ClearHighCommitQc() {
	x.xxx_hidden_HighCommitQc = nil
}

func (x *ProposalMsg) ClearSig() {
	x.xxx_hidden_Sig = nil
}

type ProposalMsg_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Block        *Block
	LastRoundTc  *TimeoutCert
	HighCommitQc *QuorumCert
	Sender       uint32
	Sig          *Signature
}

func (b0 ProposalMsg_builder) Build() *ProposalMsg {
	m0 := &ProposalMsg{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Block = b.Block
	x.xxx_hidden_LastRoundTc = b.LastRoundTc
	x.xxx_hidden_HighCommitQc = b.HighCommitQc
	x.xxx_hidden_Sender = b.Sender
	x.xxx_hidden_Sig = b.Sig
	return m0
}

type VoteMsg struct {
	state                       protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_VoteInfo         *VoteInfo              `protobuf:"bytes,1,opt,name=vote_info,json=voteInfo"`
	xxx_hidden_LedgerCommitInfo *LedgerCommitInfo      `protobuf:"bytes,2,opt,name=ledger_commit_info,json=ledgerCommitInfo"`
	xxx_hidden_HighCommitQc     *QuorumCert            `protobuf:"bytes,3,opt,name=high_commit_qc,json=highCommitQc"`
	xxx_hidden_Sender           uint32                 `protobuf:"varint,4,opt,name=sender"`
	xxx_hidden_Sig              *Signature             `protobuf:"bytes,5,opt,name=sig"`
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *VoteMsg) Reset() {
	*x = VoteMsg{}
	mi := &file_proto_diempb_diem_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VoteMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoteMsg) ProtoMessage() {}

func (x *VoteMsg) ProtoReflect() protoreflect.Message {
	mi := &file_proto_diempb_diem_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *VoteMsg) GetVoteInfo() *VoteInfo {
	if x != nil {
		return x.xxx_hidden_VoteInfo
	}
	return nil
}

func (x *VoteMsg) GetLedgerCommitInfo() *LedgerCommitInfo {
	if x != nil {
		return x.xxx_hidden_LedgerCommitInfo
	}
	return nil
}

func (x *VoteMsg) GetHighCommitQc() *QuorumCert {
	if x != nil {
		return x.xxx_hidden_HighCommitQc
	}
	return nil
}

func (x *VoteMsg) GetSender() uint32 {
	if x != nil {
		return x.xxx_hidden_Sender
	}
	return 0
}

func (x *VoteMsg) GetSig() *Signature {
	if x != nil {
		return x.xxx_hidden_Sig
	}
	return nil
}

func (x *VoteMsg) SetVoteInfo(v *VoteInfo) {
	x.xxx_hidden_VoteInfo = v
}

func (x *VoteMsg) SetLedgerCommitInfo(v *LedgerCommitInfo) {
	x.xxx_hidden_LedgerCommitInfo = v
}

func (x *VoteMsg) SetHighCommitQc(v *QuorumCert) {
	x.xxx_hidden_HighCommitQc = v
}

func (x *VoteMsg) SetSender(v uint32) {
	x.xxx_hidden_Sender = v
}

func (x *VoteMsg) SetSig(v *Signature) {
	x.xxx_hidden_Sig = v
}

func (x *VoteMsg) HasVoteInfo() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_VoteInfo != nil
}

func (x *VoteMsg) HasLedgerCommitInfo() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_LedgerCommitInfo != nil
}

func (x *VoteMsg) HasHighCommitQc() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_HighCommitQc != nil
}

func (x *VoteMsg) HasSig() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Sig != nil
}

func (x *VoteMsg) ClearVoteInfo() {
	x.xxx_hidden_VoteInfo = nil
}

func (x *VoteMsg) ClearLedgerCommitInfo() {
	x.xxx_hidden_LedgerCommitInfo = nil
}

func (x *VoteMsg) ClearHighCommitQc() {
	x.xxx_hidden_HighCommitQc = nil
}

func (x *VoteMsg) ClearSig() {
	x.xxx_hidden_Sig = nil
}

type VoteMsg_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	VoteInfo         *VoteInfo
	LedgerCommitInfo *LedgerCommitInfo
	HighCommitQc     *QuorumCert
	Sender           uint32
	Sig              *Signature
}

func (b0 VoteMsg_builder) Build() *VoteMsg {
	m0 := &VoteMsg{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_VoteInfo = b.VoteInfo
	x.xxx_hidden_LedgerCommitInfo = b.LedgerCommitInfo
	x.xxx_hidden_HighCommitQc = b.HighCommitQc
	x.xxx_hidden_Sender = b.Sender
	x.xxx_hidden_Sig = b.Sig
	return m0
}

type TimeoutInfo struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Round  uint64                 `protobuf:"varint,1,opt,name=round"`
	xxx_hidden_HighQc *QuorumCert            `protobuf:"bytes,2,opt,name=high_qc,json=highQc"`
	xxx_hidden_Sender uint32                 `protobuf:"varint,3,opt,name=sender"`
	xxx_hidden_Sig    *Signature             `protobuf:"bytes,4,opt,name=sig"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *TimeoutInfo) Reset() {
	*x = TimeoutInfo{}
	mi := &file_proto_diempb_diem_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeoutInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeoutInfo) ProtoMessage() {}

func (x *TimeoutInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_diempb_diem_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *TimeoutInfo) GetRound() uint64 {
	if x != nil {
		return x.xxx_hidden_Round
	}
	return 0
}

func (x *TimeoutInfo) GetHighQc() *QuorumCert {
	if x != nil {
		return x.xxx_hidden_HighQc
	}
	return nil
}

func (x *TimeoutInfo) GetSender() uint32 {
	if x != nil {
		return x.xxx_hidden_Sender
	}
	return 0
}

func (x *TimeoutInfo) GetSig() *Signature {
	if x != nil {
		return x.xxx_hidden_Sig
	}
	return nil
}

func (x *TimeoutInfo) SetRound(v uint64) {
	x.xxx_hidden_Round = v
}

func (x *TimeoutInfo) SetHighQc(v *QuorumCert) {
	x.xxx_hidden_HighQc = v
}

func (x *TimeoutInfo) SetSender(v uint32) {
	x.xxx_hidden_Sender = v
}

func (x *TimeoutInfo) SetSig(v *Signature) {
	x.xxx_hidden_Sig = v
}

func (x *TimeoutInfo) HasHighQc() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_HighQc != nil
}

func (x *TimeoutInfo) HasSig() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Sig != nil
}

func (x *TimeoutInfo) ClearHighQc() {
	x.xxx_hidden_HighQc = nil
}

func (x *TimeoutInfo) ClearSig() {
	x.xxx_hidden_Sig = nil
}

type TimeoutInfo_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Round  uint64
	HighQc *QuorumCert
	Sender uint32
	Sig    *Signature
}

func (b0 TimeoutInfo_builder) Build() *TimeoutInfo {
	m0 := &TimeoutInfo{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Round = b.Round
	x.xxx_hidden_HighQc = b.HighQc
	x.xxx_hidden_Sender = b.Sender
	x.xxx_hidden_Sig = b.Sig
	return m0
}

type TimeoutMsg struct {
	state                   protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_TmoInfo      *TimeoutInfo           `protobuf:"bytes,1,opt,name=tmo_info,json=tmoInfo"`
	xxx_hidden_LastRoundTc  *TimeoutCert           `protobuf:"bytes,2,opt,name=last_round_tc,json=lastRoundTc"`
	xxx_hidden_HighCommitQc *QuorumCert            `protobuf:"bytes,3,opt,name=high_commit_qc,json=highCommitQc"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *TimeoutMsg) Reset() {
	*x = TimeoutMsg{}
	mi := &file_proto_diempb_diem_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeoutMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeoutMsg) ProtoMessage() {}

func (x *TimeoutMsg) ProtoReflect() protoreflect.Message {
	mi := &file_proto_diempb_diem_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *TimeoutMsg) GetTmoInfo() *TimeoutInfo {
	if x != nil {
		return x.xxx_hidden_TmoInfo
	}
	return nil
}

func (x *TimeoutMsg) GetLastRoundTc() *TimeoutCert {
	if x != nil {
		return x.xxx_hidden_LastRoundTc
	}
	return nil
}

func (x *TimeoutMsg) GetHighCommitQc() *QuorumCert {
	if x != nil {
		return x.xxx_hidden_HighCommitQc
	}
	return nil
}

func (x *TimeoutMsg) SetTmoInfo(v *TimeoutInfo) {
	x.xxx_hidden_TmoInfo = v
}

func (x *TimeoutMsg) SetLastRoundTc(v *TimeoutCert) {
	x.xxx_hidden_LastRoundTc = v
}

func (x *TimeoutMsg) SetHighCommitQc(v *QuorumCert) {
	x.xxx_hidden_HighCommitQc = v
}

func (x *TimeoutMsg) HasTmoInfo() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_TmoInfo != nil
}

func (x *TimeoutMsg) HasLastRoundTc() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_LastRoundTc != nil
}

func (x *TimeoutMsg) HasHighCommitQc() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_HighCommitQc != nil
}

func (x *TimeoutMsg) ClearTmoInfo() {
	x.xxx_hidden_TmoInfo = nil
}

func (x *TimeoutMsg) ClearLastRoundTc() {
	x.xxx_hidden_LastRoundTc = nil
}

func (x *TimeoutMsg) ClearHighCommitQc() {
	x.xxx_hidden_HighCommitQc = nil
}

type TimeoutMsg_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	TmoInfo      *TimeoutInfo
	LastRoundTc  *TimeoutCert
	HighCommitQc *QuorumCert
}

func (b0 TimeoutMsg_builder) Build() *TimeoutMsg {
	m0 := &TimeoutMsg{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_TmoInfo = b.TmoInfo
	x.xxx_hidden_LastRoundTc = b.LastRoundTc
	x.xxx_hidden_HighCommitQc = b.HighCommitQc
	return m0
}

var File_proto_diempb_diem_proto protoreflect.FileDescriptor

const file_proto_diempb_diem_proto_rawDesc = "" +
	"\n" +
	"\x17proto/diempb/diem.proto\x12\x06diempb\x1a\fgorums.proto\x1a\x1bgoogle/protobuf/empty.proto\"5\n" +
	"\tSignature\x12\x16\n" +
	"\x06signer\x18\x01 \x01(\rR\x06signer\x12\x10\n" +
	"\x03sig\x18\x02 \x01(\fR\x03sig\"\x94\x01\n" +
	"\bVoteInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\fR\x02id\x12\x14\n" +
	"\x05round\x18\x02 \x01(\x04R\x05round\x12\x1b\n" +
	"\tparent_id\x18\x03 \x01(\fR\bparentId\x12!\n" +
	"\fparent_round\x18\x04 \x01(\x04R\vparentRound\x12\"\n" +
	"\rexec_state_id\x18\x05 \x01(\fR\vexecStateId\"`\n" +
	"\x10LedgerCommitInfo\x12&\n" +
	"\x0fcommit_state_id\x18\x01 \x01(\fR\rcommitStateId\x12$\n" +
	"\x0evote_info_hash\x18\x02 \x01(\fR\fvoteInfoHash\"\x80\x02\n" +
	"\n" +
	"QuorumCert\x12-\n" +
	"\tvote_info\x18\x01 \x01(\v2\x10.diempb.VoteInfoR\bvoteInfo\x12F\n" +
	"\x12ledger_commit_info\x18\x02 \x01(\v2\x18.diempb.LedgerCommitInfoR\x10ledgerCommitInfo\x121\n" +
	"\n" +
	"signatures\x18\x03 \x03(\v2\x11.diempb.SignatureR\n" +
	"signatures\x12\x16\n" +
	"\x06author\x18\x04 \x01(\rR\x06author\x120\n" +
	"\n" +
	"author_sig\x18\x05 \x01(\v2\x11.diempb.SignatureR\tauthorSig\"V\n" +
	"\vTimeoutVote\x12\"\n" +
	"\rhigh_qc_round\x18\x01 \x01(\x04R\vhighQcRound\x12#\n" +
	"\x03sig\x18\x02 \x01(\v2\x11.diempb.SignatureR\x03sig\"N\n" +
	"\vTimeoutCert\x12\x14\n" +
	"\x05round\x18\x01 \x01(\x04R\x05round\x12)\n" +
	"\x05votes\x18\x02 \x03(\v2\x13.diempb.TimeoutVoteR\x05votes\"s\n" +
	"\x05Block\x12\x16\n" +
	"\x06author\x18\x01 \x01(\rR\x06author\x12\x14\n" +
	"\x05round\x18\x02 \x01(\x04R\x05round\x12\x18\n" +
	"\apayload\x18\x03 \x03(\fR\apayload\x12\"\n" +
	"\x02qc\x18\x04 \x01(\v2\x12.diempb.QuorumCertR\x02qc\"\xe2\x01\n" +
	"\vProposalMsg\x12#\n" +
	"\x05block\x18\x01 \x01(\v2\r.diempb.BlockR\x05block\x127\n" +
	"\rlast_round_tc\x18\x02 \x01(\v2\x13.diempb.TimeoutCertR\vlastRoundTc\x128\n" +
	"\x0ehigh_commit_qc\x18\x03 \x01(\v2\x12.diempb.QuorumCertR\fhighCommitQc\x12\x16\n" +
	"\x06sender\x18\x04 \x01(\rR\x06sender\x12#\n" +
	"\x03sig\x18\x05 \x01(\v2\x11.diempb.SignatureR\x03sig\"\xf7\x01\n" +
	"\aVoteMsg\x12-\n" +
	"\tvote_info\x18\x01 \x01(\v2\x10.diempb.VoteInfoR\bvoteInfo\x12F\n" +
	"\x12ledger_commit_info\x18\x02 \x01(\v2\x18.diempb.LedgerCommitInfoR\x10ledgerCommitInfo\x128\n" +
	"\x0ehigh_commit_qc\x18\x03 \x01(\v2\x12.diempb.QuorumCertR\fhighCommitQc\x12\x16\n" +
	"\x06sender\x18\x04 \x01(\rR\x06sender\x12#\n" +
	"\x03sig\x18\x05 \x01(\v2\x11.diempb.SignatureR\x03sig\"\x8d\x01\n" +
	"\vTimeoutInfo\x12\x14\n" +
	"\x05round\x18\x01 \x01(\x04R\x05round\x12+\n" +
	"\ahigh_qc\x18\x02 \x01(\v2\x12.diempb.QuorumCertR\x06highQc\x12\x16\n" +
	"\x06sender\x18\x03 \x01(\rR\x06sender\x12#\n" +
	"\x03sig\x18\x04 \x01(\v2\x11.diempb.SignatureR\x03sig\"\xaf\x01\n" +
	"\n" +
	"TimeoutMsg\x12.\n" +
	"\btmo_info\x18\x01 \x01(\v2\x13.diempb.TimeoutInfoR\atmoInfo\x127\n" +
	"\rlast_round_tc\x18\x02 \x01(\v2\x13.diempb.TimeoutCertR\vlastRoundTc\x128\n" +
	"\x0ehigh_commit_qc\x18\x03 \x01(\v2\x12.diempb.QuorumCertR\fhighCommitQc2\xb9\x01\n" +
	"\x04Diem\x12=\n" +
	"\bProposal\x12\x13.diempb.ProposalMsg\x1a\x16.google.protobuf.Empty\"\x04\x98\xb5\x18\x01\x125\n" +
	"\x04Vote\x12\x0f.diempb.VoteMsg\x1a\x16.google.protobuf.Empty\"\x04\x90\xb5\x18\x01\x12;\n" +
	"\aTimeout\x12\x12.diempb.TimeoutMsg\x1a\x16.google.protobuf.Empty\"\x04\x98\xb5\x18\x01B0Z)github.com/DanyGoT/HotStuffs/proto/diempb\x92\x03\x02\b\x02b\beditionsp\xe9\a"

var file_proto_diempb_diem_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_diempb_diem_proto_goTypes = []any{
	(*Signature)(nil),        // 0: diempb.Signature
	(*VoteInfo)(nil),         // 1: diempb.VoteInfo
	(*LedgerCommitInfo)(nil), // 2: diempb.LedgerCommitInfo
	(*QuorumCert)(nil),       // 3: diempb.QuorumCert
	(*TimeoutVote)(nil),      // 4: diempb.TimeoutVote
	(*TimeoutCert)(nil),      // 5: diempb.TimeoutCert
	(*Block)(nil),            // 6: diempb.Block
	(*ProposalMsg)(nil),      // 7: diempb.ProposalMsg
	(*VoteMsg)(nil),          // 8: diempb.VoteMsg
	(*TimeoutInfo)(nil),      // 9: diempb.TimeoutInfo
	(*TimeoutMsg)(nil),       // 10: diempb.TimeoutMsg
	(*emptypb.Empty)(nil),    // 11: google.protobuf.Empty
}
var file_proto_diempb_diem_proto_depIdxs = []int32{
	1,  // 0: diempb.QuorumCert.vote_info:type_name -> diempb.VoteInfo
	2,  // 1: diempb.QuorumCert.ledger_commit_info:type_name -> diempb.LedgerCommitInfo
	0,  // 2: diempb.QuorumCert.signatures:type_name -> diempb.Signature
	0,  // 3: diempb.QuorumCert.author_sig:type_name -> diempb.Signature
	0,  // 4: diempb.TimeoutVote.sig:type_name -> diempb.Signature
	4,  // 5: diempb.TimeoutCert.votes:type_name -> diempb.TimeoutVote
	3,  // 6: diempb.Block.qc:type_name -> diempb.QuorumCert
	6,  // 7: diempb.ProposalMsg.block:type_name -> diempb.Block
	5,  // 8: diempb.ProposalMsg.last_round_tc:type_name -> diempb.TimeoutCert
	3,  // 9: diempb.ProposalMsg.high_commit_qc:type_name -> diempb.QuorumCert
	0,  // 10: diempb.ProposalMsg.sig:type_name -> diempb.Signature
	1,  // 11: diempb.VoteMsg.vote_info:type_name -> diempb.VoteInfo
	2,  // 12: diempb.VoteMsg.ledger_commit_info:type_name -> diempb.LedgerCommitInfo
	3,  // 13: diempb.VoteMsg.high_commit_qc:type_name -> diempb.QuorumCert
	0,  // 14: diempb.VoteMsg.sig:type_name -> diempb.Signature
	3,  // 15: diempb.TimeoutInfo.high_qc:type_name -> diempb.QuorumCert
	0,  // 16: diempb.TimeoutInfo.sig:type_name -> diempb.Signature
	9,  // 17: diempb.TimeoutMsg.tmo_info:type_name -> diempb.TimeoutInfo
	5,  // 18: diempb.TimeoutMsg.last_round_tc:type_name -> diempb.TimeoutCert
	3,  // 19: diempb.TimeoutMsg.high_commit_qc:type_name -> diempb.QuorumCert
	7,  // 20: diempb.Diem.Proposal:input_type -> diempb.ProposalMsg
	8,  // 21: diempb.Diem.Vote:input_type -> diempb.VoteMsg
	10, // 22: diempb.Diem.Timeout:input_type -> diempb.TimeoutMsg
	11, // 23: diempb.Diem.Proposal:output_type -> google.protobuf.Empty
	11, // 24: diempb.Diem.Vote:output_type -> google.protobuf.Empty
	11, // 25: diempb.Diem.Timeout:output_type -> google.protobuf.Empty
	23, // [23:26] is the sub-list for method output_type
	20, // [20:23] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_proto_diempb_diem_proto_init() }
func file_proto_diempb_diem_proto_init() {
	if File_proto_diempb_diem_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_diempb_diem_proto_rawDesc), len(file_proto_diempb_diem_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_diempb_diem_proto_goTypes,
		DependencyIndexes: file_proto_diempb_diem_proto_depIdxs,
		MessageInfos:      file_proto_diempb_diem_proto_msgTypes,
	}.Build()
	File_proto_diempb_diem_proto = out.File
	file_proto_diempb_diem_proto_goTypes = nil
	file_proto_diempb_diem_proto_depIdxs = nil
}
