// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.34.1
// source: proto/hotstuffpb/hotstuff.proto

package hotstuffpb

import (
	_ "github.com/relab/gorums"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// signer is a *claim*: meaningful only once sig verifies against the public key
// registered for that ID. Gorums exposes no authenticated sender identity, so
// authentication is by signature, never by connection.
type Signature struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Signer uint32                 `protobuf:"varint,1,opt,name=signer"`
	xxx_hidden_Sig    []byte                 `protobuf:"bytes,2,opt,name=sig"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Signature) Reset() {
	*x = Signature{}
	mi := &file_proto_hotstuffpb_hotstuff_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Signature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Signature) ProtoMessage() {}

func (x *Signature) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hotstuffpb_hotstuff_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Signature) GetSigner() uint32 {
	if x != nil {
		return x.xxx_hidden_Signer
	}
	return 0
}

func (x *Signature) GetSig() []byte {
	if x != nil {
		return x.xxx_hidden_Sig
	}
	return nil
}

func (x *Signature) SetSigner(v uint32) {
	x.xxx_hidden_Signer = v
}

func (x *Signature) SetSig(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Sig = v
}

type Signature_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Signer uint32
	Sig    []byte
}

func (b0 Signature_builder) Build() *Signature {
	m0 := &Signature{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Signer = b.Signer
	x.xxx_hidden_Sig = b.Sig
	return m0
}

type QuorumCert struct {
	state                protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_View      uint64                 `protobuf:"varint,1,opt,name=view"`
	xxx_hidden_BlockHash []byte                 `protobuf:"bytes,2,opt,name=block_hash,json=blockHash"`
	xxx_hidden_Sigs      *[]*Signature          `protobuf:"bytes,3,rep,name=sigs"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *QuorumCert) Reset() {
	*x = QuorumCert{}
	mi := &file_proto_hotstuffpb_hotstuff_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuorumCert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuorumCert) ProtoMessage() {}

func (x *QuorumCert) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hotstuffpb_hotstuff_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *QuorumCert) GetView() uint64 {
	if x != nil {
		return x.xxx_hidden_View
	}
	return 0
}

func (x *QuorumCert) GetBlockHash() []byte {
	if x != nil {
		return x.xxx_hidden_BlockHash
	}
	return nil
}

func (x *QuorumCert) GetSigs() []*Signature {
	if x != nil {
		if x.xxx_hidden_Sigs != nil {
			return *x.xxx_hidden_Sigs
		}
	}
	return nil
}

func (x *QuorumCert) SetView(v uint64) {
	x.xxx_hidden_View = v
}

func (x *QuorumCert) SetBlockHash(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_BlockHash = v
}

func (x *QuorumCert) SetSigs(v []*Signature) {
	x.xxx_hidden_Sigs = &v
}

type QuorumCert_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	View      uint64
	BlockHash []byte
	Sigs      []*Signature
}

func (b0 QuorumCert_builder) Build() *QuorumCert {
	m0 := &QuorumCert{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_View = b.View
	x.xxx_hidden_BlockHash = b.BlockHash
	x.xxx_hidden_Sigs = &b.Sigs
	return m0
}

type TimeoutCert struct {
	state           protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_View uint64                 `protobuf:"varint,1,opt,name=view"`
	xxx_hidden_Sigs *[]*Signature          `protobuf:"bytes,2,rep,name=sigs"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TimeoutCert) Reset() {
	*x = TimeoutCert{}
	mi := &file_proto_hotstuffpb_hotstuff_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeoutCert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeoutCert) ProtoMessage() {}

func (x *TimeoutCert) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hotstuffpb_hotstuff_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *TimeoutCert) GetView() uint64 {
	if x != nil {
		return x.xxx_hidden_View
	}
	return 0
}

func (x *TimeoutCert) GetSigs() []*Signature {
	if x != nil {
		if x.xxx_hidden_Sigs != nil {
			return *x.xxx_hidden_Sigs
		}
	}
	return nil
}

func (x *TimeoutCert) SetView(v uint64) {
	x.xxx_hidden_View = v
}

func (x *TimeoutCert) SetSigs(v []*Signature) {
	x.xxx_hidden_Sigs = &v
}

type TimeoutCert_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	View uint64
	Sigs []*Signature
}

func (b0 TimeoutCert_builder) Build() *TimeoutCert {
	m0 := &TimeoutCert{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_View = b.View
	x.xxx_hidden_Sigs = &b.Sigs
	return m0
}

// No height field: view is the height. No timestamp: the hash is a pure
// function of protocol state and is reproducible in tests.
type Block struct {
	state               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Parent   []byte                 `protobuf:"bytes,1,opt,name=parent"`
	xxx_hidden_View     uint64                 `protobuf:"varint,2,opt,name=view"`
	xxx_hidden_Proposer uint32                 `protobuf:"varint,3,opt,name=proposer"`
	xxx_hidden_Cmds     [][]byte               `protobuf:"bytes,4,rep,name=cmds"`
	xxx_hidden_Cert     *QuorumCert            `protobuf:"bytes,5,opt,name=cert"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Block) Reset() {
	*x = Block{}
	mi := &file_proto_hotstuffpb_hotstuff_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Block) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Block) ProtoMessage() {}

func (x *Block) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hotstuffpb_hotstuff_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Block) GetParent() []byte {
	if x != nil {
		return x.xxx_hidden_Parent
	}
	return nil
}

func (x *Block) GetView() uint64 {
	if x != nil {
		return x.xxx_hidden_View
	}
	return 0
}

func (x *Block) GetProposer() uint32 {
	if x != nil {
		return x.xxx_hidden_Proposer
	}
	return 0
}

func (x *Block) GetCmds() [][]byte {
	if x != nil {
		return x.xxx_hidden_Cmds
	}
	return nil
}

func (x *Block) GetCert() *QuorumCert {
	if x != nil {
		return x.xxx_hidden_Cert
	}
	return nil
}

func (x *Block) SetParent(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Parent = v
}

func (x *Block) SetView(v uint64) {
	x.xxx_hidden_View = v
}

func (x *Block) SetProposer(v uint32) {
	x.xxx_hidden_Proposer = v
}

func (x *Block) SetCmds(v [][]byte) {
	x.xxx_hidden_Cmds = v
}

func (x *Block) SetCert(v *QuorumCert) {
	x.xxx_hidden_Cert = v
}

func (x *Block) HasCert() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Cert != nil
}

func (x *Block) ClearCert() {
	x.xxx_hidden_Cert = nil
}

type Block_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Parent   []byte
	View     uint64
	Proposer uint32
	Cmds     [][]byte
	Cert     *QuorumCert
}

func (b0 Block_builder) Build() *Block {
	m0 := &Block{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Parent = b.Parent
	x.xxx_hidden_View = b.View
	x.xxx_hidden_Proposer = b.Proposer
	x.xxx_hidden_Cmds = b.Cmds
	x.xxx_hidden_Cert = b.Cert
	return m0
}

type Proposal struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Block *Block                 `protobuf:"bytes,1,opt,name=block"`
	xxx_hidden_Sig   *Signature             `protobuf:"bytes,2,opt,name=sig"`
	xxx_hidden_Tc    *TimeoutCert           `protobuf:"bytes,3,opt,name=tc"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Proposal) Reset() {
	*x = Proposal{}
	mi := &file_proto_hotstuffpb_hotstuff_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Proposal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Proposal) ProtoMessage() {}

func (x *Proposal) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hotstuffpb_hotstuff_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Proposal) GetBlock() *Block {
	if x != nil {
		return x.xxx_hidden_Block
	}
	return nil
}

func (x *Proposal) GetSig() *Signature {
	if x != nil {
		return x.xxx_hidden_Sig
	}
	return nil
}

func (x *Proposal) GetTc() *TimeoutCert {
	if x != nil {
		return x.xxx_hidden_Tc
	}
	return nil
}

func (x *Proposal) SetBlock(v *Block) {
	x.xxx_hidden_Block = v
}

func (x *Proposal) SetSig(v *Signature) {
	x.xxx_hidden_Sig = v
}

func (x *Proposal) SetTc(v *TimeoutCert) {
	x.xxx_hidden_Tc = v
}

func (x *Proposal) HasBlock() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Block != nil
}

func (x *Proposal) HasSig() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Sig != nil
}

func (x *Proposal) HasTc() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Tc != nil
}

func (x *Proposal) ClearBlock() {
	x.xxx_hidden_Block = nil
}

func (x *Proposal) ClearSig() {
	x.xxx_hidden_Sig = nil
}

func (x *Proposal) ClearTc() {
	x.xxx_hidden_Tc = nil
}

type Proposal_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Block *Block
	Sig   *Signature
	Tc    *TimeoutCert
}

func (b0 Proposal_builder) Build() *Proposal {
	m0 := &Proposal{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Block = b.Block
	x.xxx_hidden_Sig = b.Sig
	x.xxx_hidden_Tc = b.Tc
	return m0
}

type VoteMsg struct {
	state                protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_View      uint64                 `protobuf:"varint,1,opt,name=view"`
	xxx_hidden_BlockHash []byte                 `protobuf:"bytes,2,opt,name=block_hash,json=blockHash"`
	xxx_hidden_Sig       *Signature             `protobuf:"bytes,3,opt,name=sig"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *VoteMsg) Reset() {
	*x = VoteMsg{}
	mi := &file_proto_hotstuffpb_hotstuff_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VoteMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoteMsg) ProtoMessage() {}

func (x *VoteMsg) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hotstuffpb_hotstuff_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *VoteMsg) GetView() uint64 {
	if x != nil {
		return x.xxx_hidden_View
	}
	return 0
}

func (x *VoteMsg) GetBlockHash() []byte {
	if x != nil {
		return x.xxx_hidden_BlockHash
	}
	return nil
}

func (x *VoteMsg) GetSig() *Signature {
	if x != nil {
		return x.xxx_hidden_Sig
	}
	return nil
}

func (x *VoteMsg) SetView(v uint64) {
	x.xxx_hidden_View = v
}

func (x *VoteMsg) SetBlockHash(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_BlockHash = v
}

func (x *VoteMsg) SetSig(v *Signature) {
	x.xxx_hidden_Sig = v
}

func (x *VoteMsg) HasSig() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Sig != nil
}

func (x *VoteMsg) ClearSig() {
	x.xxx_hidden_Sig = nil
}

type VoteMsg_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	View      uint64
	BlockHash []byte
	Sig       *Signature
}

func (b0 VoteMsg_builder) Build() *VoteMsg {
	m0 := &VoteMsg{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_View = b.View
	x.xxx_hidden_BlockHash = b.BlockHash
	x.xxx_hidden_Sig = b.Sig
	return m0
}

// One signature, not two: it covers only the view, so it aggregates into a
// TimeoutCert, and high_qc authenticates itself.
type TimeoutMsg struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_View   uint64                 `protobuf:"varint,1,opt,name=view"`
	xxx_hidden_Sig    *Signature             `protobuf:"bytes,2,opt,name=sig"`
	xxx_hidden_HighQc *QuorumCert            `protobuf:"bytes,3,opt,name=high_qc,json=highQc"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *TimeoutMsg) Reset() {
	*x = TimeoutMsg{}
	mi := &file_proto_hotstuffpb_hotstuff_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeoutMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeoutMsg) ProtoMessage() {}

func (x *TimeoutMsg) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hotstuffpb_hotstuff_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *TimeoutMsg) GetView() uint64 {
	if x != nil {
		return x.xxx_hidden_View
	}
	return 0
}

func (x *TimeoutMsg) GetSig() *Signature {
	if x != nil {
		return x.xxx_hidden_Sig
	}
	return nil
}

func (x *TimeoutMsg) GetHighQc() *QuorumCert {
	if x != nil {
		return x.xxx_hidden_HighQc
	}
	return nil
}

func (x *TimeoutMsg) SetView(v uint64) {
	x.xxx_hidden_View = v
}

func (x *TimeoutMsg) SetSig(v *Signature) {
	x.xxx_hidden_Sig = v
}

func (x *TimeoutMsg) SetHighQc(v *QuorumCert) {
	x.xxx_hidden_HighQc = v
}

func (x *TimeoutMsg) HasSig() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Sig != nil
}

func (x *TimeoutMsg) HasHighQc() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_HighQc != nil
}

func (x *TimeoutMsg) ClearSig() {
	x.xxx_hidden_Sig = nil
}

func (x *TimeoutMsg) ClearHighQc() {
	x.xxx_hidden_HighQc = nil
}

type TimeoutMsg_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	View   uint64
	Sig    *Signature
	HighQc *QuorumCert
}

func (b0 TimeoutMsg_builder) Build() *TimeoutMsg {
	m0 := &TimeoutMsg{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_View = b.View
	x.xxx_hidden_Sig = b.Sig
	x.xxx_hidden_HighQc = b.HighQc
	return m0
}

type BlockHash struct {
	state           protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Hash []byte                 `protobuf:"bytes,1,opt,name=hash"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *BlockHash) Reset() {
	*x = BlockHash{}
	mi := &file_proto_hotstuffpb_hotstuff_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockHash) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockHash) ProtoMessage() {}

func (x *BlockHash) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hotstuffpb_hotstuff_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *BlockHash) GetHash() []byte {
	if x != nil {
		return x.xxx_hidden_Hash
	}
	return nil
}

func (x *BlockHash) SetHash(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Hash = v
}

type BlockHash_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Hash []byte
}

func (b0 BlockHash_builder) Build() *BlockHash {
	m0 := &BlockHash{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Hash = b.Hash
	return m0
}

var File_proto_hotstuffpb_hotstuff_proto protoreflect.FileDescriptor

const file_proto_hotstuffpb_hotstuff_proto_rawDesc = "" +
	"\n" +
	"\x1fproto/hotstuffpb/hotstuff.proto\x12\n" +
	"hotstuffpb\x1a\fgorums.proto\x1a\x1bgoogle/protobuf/empty.proto\"5\n" +
	"\tSignature\x12\x16\n" +
	"\x06signer\x18\x01 \x01(\rR\x06signer\x12\x10\n" +
	"\x03sig\x18\x02 \x01(\fR\x03sig\"j\n" +
	"\n" +
	"QuorumCert\x12\x12\n" +
	"\x04view\x18\x01 \x01(\x04R\x04view\x12\x1d\n" +
	"\n" +
	"block_hash\x18\x02 \x01(\fR\tblockHash\x12)\n" +
	"\x04sigs\x18\x03 \x03(\v2\x15.hotstuffpb.SignatureR\x04sigs\"L\n" +
	"\vTimeoutCert\x12\x12\n" +
	"\x04view\x18\x01 \x01(\x04R\x04view\x12)\n" +
	"\x04sigs\x18\x02 \x03(\v2\x15.hotstuffpb.SignatureR\x04sigs\"\x8f\x01\n" +
	"\x05Block\x12\x16\n" +
	"\x06parent\x18\x01 \x01(\fR\x06parent\x12\x12\n" +
	"\x04view\x18\x02 \x01(\x04R\x04view\x12\x1a\n" +
	"\bproposer\x18\x03 \x01(\rR\bproposer\x12\x12\n" +
	"\x04cmds\x18\x04 \x03(\fR\x04cmds\x12*\n" +
	"\x04cert\x18\x05 \x01(\v2\x16.hotstuffpb.QuorumCertR\x04cert\"\x85\x01\n" +
	"\bProposal\x12'\n" +
	"\x05block\x18\x01 \x01(\v2\x11.hotstuffpb.BlockR\x05block\x12'\n" +
	"\x03sig\x18\x02 \x01(\v2\x15.hotstuffpb.SignatureR\x03sig\x12'\n" +
	"\x02tc\x18\x03 \x01(\v2\x17.hotstuffpb.TimeoutCertR\x02tc\"e\n" +
	"\aVoteMsg\x12\x12\n" +
	"\x04view\x18\x01 \x01(\x04R\x04view\x12\x1d\n" +
	"\n" +
	"block_hash\x18\x02 \x01(\fR\tblockHash\x12'\n" +
	"\x03sig\x18\x03 \x01(\v2\x15.hotstuffpb.SignatureR\x03sig\"z\n" +
	"\n" +
	"TimeoutMsg\x12\x12\n" +
	"\x04view\x18\x01 \x01(\x04R\x04view\x12'\n" +
	"\x03sig\x18\x02 \x01(\v2\x15.hotstuffpb.SignatureR\x03sig\x12/\n" +
	"\ahigh_qc\x18\x03 \x01(\v2\x16.hotstuffpb.QuorumCertR\x06highQc\"\x1f\n" +
	"\tBlockHash\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\fR\x04hash2\xfe\x01\n" +
	"\bHotStuff\x12=\n" +
	"\aPropose\x12\x14.hotstuffpb.Proposal\x1a\x16.google.protobuf.Empty\"\x04\x98\xb5\x18\x01\x129\n" +
	"\x04Vote\x12\x13.hotstuffpb.VoteMsg\x1a\x16.google.protobuf.Empty\"\x04\x98\xb5\x18\x01\x12?\n" +
	"\aTimeout\x12\x16.hotstuffpb.TimeoutMsg\x1a\x16.google.protobuf.Empty\"\x04\x98\xb5\x18\x01\x127\n" +
	"\x05Fetch\x12\x15.hotstuffpb.BlockHash\x1a\x11.hotstuffpb.Block\"\x04\xa0\xb5\x18\x01B4Z-github.com/DanyGoT/HotStuffs/proto/hotstuffpb\x92\x03\x02\b\x02b\beditionsp\xe9\a"

var file_proto_hotstuffpb_hotstuff_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_hotstuffpb_hotstuff_proto_goTypes = []any{
	(*Signature)(nil),     // 0: hotstuffpb.Signature
	(*QuorumCert)(nil),    // 1: hotstuffpb.QuorumCert
	(*TimeoutCert)(nil),   // 2: hotstuffpb.TimeoutCert
	(*Block)(nil),         // 3: hotstuffpb.Block
	(*Proposal)(nil),      // 4: hotstuffpb.Proposal
	(*VoteMsg)(nil),       // 5: hotstuffpb.VoteMsg
	(*TimeoutMsg)(nil),    // 6: hotstuffpb.TimeoutMsg
	(*BlockHash)(nil),     // 7: hotstuffpb.BlockHash
	(*emptypb.Empty)(nil), // 8: google.protobuf.Empty
}
var file_proto_hotstuffpb_hotstuff_proto_depIdxs = []int32{
	0,  // 0: hotstuffpb.QuorumCert.sigs:type_name -> hotstuffpb.Signature
	0,  // 1: hotstuffpb.TimeoutCert.sigs:type_name -> hotstuffpb.Signature
	1,  // 2: hotstuffpb.Block.cert:type_name -> hotstuffpb.QuorumCert
	3,  // 3: hotstuffpb.Proposal.block:type_name -> hotstuffpb.Block
	0,  // 4: hotstuffpb.Proposal.sig:type_name -> hotstuffpb.Signature
	2,  // 5: hotstuffpb.Proposal.tc:type_name -> hotstuffpb.TimeoutCert
	0,  // 6: hotstuffpb.VoteMsg.sig:type_name -> hotstuffpb.Signature
	0,  // 7: hotstuffpb.TimeoutMsg.sig:type_name -> hotstuffpb.Signature
	1,  // 8: hotstuffpb.TimeoutMsg.high_qc:type_name -> hotstuffpb.QuorumCert
	4,  // 9: hotstuffpb.HotStuff.Propose:input_type -> hotstuffpb.Proposal
	5,  // 10: hotstuffpb.HotStuff.Vote:input_type -> hotstuffpb.VoteMsg
	6,  // 11: hotstuffpb.HotStuff.Timeout:input_type -> hotstuffpb.TimeoutMsg
	7,  // 12: hotstuffpb.HotStuff.Fetch:input_type -> hotstuffpb.BlockHash
	8,  // 13: hotstuffpb.HotStuff.Propose:output_type -> google.protobuf.Empty
	8,  // 14: hotstuffpb.HotStuff.Vote:output_type -> google.protobuf.Empty
	8,  // 15: hotstuffpb.HotStuff.Timeout:output_type -> google.protobuf.Empty
	3,  // 16: hotstuffpb.HotStuff.Fetch:output_type -> hotstuffpb.Block
	13, // [13:17] is the sub-list for method output_type
	9,  // [9:13] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_proto_hotstuffpb_hotstuff_proto_init() }
func file_proto_hotstuffpb_hotstuff_proto_init() {
	if File_proto_hotstuffpb_hotstuff_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_hotstuffpb_hotstuff_proto_rawDesc), len(file_proto_hotstuffpb_hotstuff_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_hotstuffpb_hotstuff_proto_goTypes,
		DependencyIndexes: file_proto_hotstuffpb_hotstuff_proto_depIdxs,
		MessageInfos:      file_proto_hotstuffpb_hotstuff_proto_msgTypes,
	}.Build()
	File_proto_hotstuffpb_hotstuff_proto = out.File
	file_proto_hotstuffpb_hotstuff_proto_goTypes = nil
	file_proto_hotstuffpb_hotstuff_proto_depIdxs = nil
}
