// Code generated by protoc-gen-gorums. DO NOT EDIT.
// versions:
// 	protoc-gen-gorums v0.11.0-devel
// 	protoc            v7.34.1
// source: proto/hotstuffpb/hotstuff.proto

package hotstuffpb

import (
	gorums "github.com/relab/gorums"
	gorumsimpl "github.com/relab/gorums/runtime/gorumsimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = gorumsimpl.EnforceVersion(11 - gorumsimpl.MinVersion)
	// Verify that the gorums runtime is sufficiently up-to-date.
	_ = gorumsimpl.EnforceVersion(gorumsimpl.MaxVersion - 11)
)

// The type aliases below are useful Gorums types that we make accessible
// from generated code. These names therefore become reserved identifiers,
// meaning that proto message types with these names would collide with the
// generated aliases and cause a compile error.
//
// The bundler (gorums_bundle.go) is responsible for discovering these
// aliases and any other identifiers defined herein, and adding them to
// the reserved identifiers list.
//
// If necessary, additional aliases and other identifiers should be added in
// the generator's cmd/protoc-gen-gorums/dev directory, and the bundler will
// automatically discover them and add them to the reserved identifiers list.

type (
	Config        = gorums.Config
	Node          = gorums.Node
	NodeContext   = gorums.NodeContext
	ConfigContext = gorums.ConfigContext
)

// AsyncBlock is a future for async quorum calls returning *Block.
type AsyncBlock = *gorums.Async[*Block]

// CorrectableBlock is a correctable object for quorum calls returning *Block.
type CorrectableBlock = *gorums.Correctable[*Block]

// Reference imports to suppress errors if they are not otherwise used.
var _ emptypb.Empty

// Propose is a multicast call invoked on all nodes in the configuration in ctx.
// It returns a one-way call handle; call Send to block until every send
// completes and observe any send errors, or Async to dispatch without waiting.
// Use gorums.MapRequest to send different messages to each node.
//
// Example:
//
//	err := Propose(ctx, in).Send()
//	h := Propose(ctx, in).Async(); err := h.Wait()
func Propose(ctx *ConfigContext, in *Proposal) *gorums.OnewayCall[*Proposal] {
	return gorumsimpl.Multicast(ctx, in, "hotstuffpb.HotStuff.Propose")
}

// Votes are broadcast, not unicast to the leader of the next view. That
// mapping stalls commits whenever a crashed replica is both a leader and the
// preceding view's sole collector.
//
// Example:
//
//	err := Vote(ctx, in).Send()
//	h := Vote(ctx, in).Async(); err := h.Wait()
func Vote(ctx *ConfigContext, in *VoteMsg) *gorums.OnewayCall[*VoteMsg] {
	return gorumsimpl.Multicast(ctx, in, "hotstuffpb.HotStuff.Vote")
}

// Timeout is a multicast call invoked on all nodes in the configuration in ctx.
// It returns a one-way call handle; call Send to block until every send
// completes and observe any send errors, or Async to dispatch without waiting.
// Use gorums.MapRequest to send different messages to each node.
//
// Example:
//
//	err := Timeout(ctx, in).Send()
//	h := Timeout(ctx, in).Async(); err := h.Wait()
func Timeout(ctx *ConfigContext, in *TimeoutMsg) *gorums.OnewayCall[*TimeoutMsg] {
	return gorumsimpl.Multicast(ctx, in, "hotstuffpb.HotStuff.Timeout")
}

// The only natural quorum call in the protocol: blocks are content-addressed,
// so any single correct response suffices and a wrong one is caught by
// re-hashing. Consumed with .First().
func Fetch(ctx *ConfigContext, in *BlockHash) *gorums.Call[*BlockHash, *Block] {
	return gorumsimpl.QuorumCall[*BlockHash, *Block](
		ctx, in, "hotstuffpb.HotStuff.Fetch",
	)
}

// HotStuff is the server-side API for the HotStuff Service
type HotStuffServer interface {
	Propose(gorums.ServerContext, *Proposal)
	Vote(gorums.ServerContext, *VoteMsg)
	Timeout(gorums.ServerContext, *TimeoutMsg)
	Fetch(gorums.ServerContext, *BlockHash) (*Block, error)
}

func RegisterHotStuffServer(srv *gorums.Server, impl HotStuffServer) {
	srv.RegisterHandler("hotstuffpb.HotStuff.Propose", func(ctx gorums.ServerContext, in *gorums.Message) (*gorums.Message, error) {
		req := gorums.AsProto[*Proposal](in)
		impl.Propose(ctx, req)
		return nil, nil
	})
	srv.RegisterHandler("hotstuffpb.HotStuff.Vote", func(ctx gorums.ServerContext, in *gorums.Message) (*gorums.Message, error) {
		req := gorums.AsProto[*VoteMsg](in)
		impl.Vote(ctx, req)
		return nil, nil
	})
	srv.RegisterHandler("hotstuffpb.HotStuff.Timeout", func(ctx gorums.ServerContext, in *gorums.Message) (*gorums.Message, error) {
		req := gorums.AsProto[*TimeoutMsg](in)
		impl.Timeout(ctx, req)
		return nil, nil
	})
	srv.RegisterHandler("hotstuffpb.HotStuff.Fetch", func(ctx gorums.ServerContext, in *gorums.Message) (*gorums.Message, error) {
		req := gorums.AsProto[*BlockHash](in)
		resp, err := impl.Fetch(ctx, req)
		if err != nil {
			return nil, err
		}
		return gorums.NewResponseMessage(in, resp), nil
	})
}
